name: Run Newman

on:
  push:
    branches: [test]
 
jobs:

  api-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install -g newman

    - run: npm run init-adm
    - run: npm run init-sds
    - run: npm install -g pm2 
    - run: pm2 start "npm run dev"
    - run: pm2 start "npm run init-postman"
    # run the npm build command (not used in our project)
    
      # install pm2 so we can run our node.js
      # based backend without blocking the terminal
    
      # install newman globally so we can run
      # postman collections
      # run our api tests
   